import type { PieceDefinition } from "./types";

export const PIECE_DEFINITIONS: PieceDefinition[] = [
  {
    nodeName: "Pawn001_White_Material003_0",
    type: "pawn",
    color: "white",
    square: "a2",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn002_White_Material003_0",
    type: "pawn",
    color: "white",
    square: "b2",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn003_White_Material003_0",
    type: "pawn",
    color: "white",
    square: "c2",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn004_White_Material003_0",
    type: "pawn",
    color: "white",
    square: "d2",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn005_White_Material003_0",
    type: "pawn",
    color: "white",
    square: "e2",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn006_White_Material003_0",
    type: "pawn",
    color: "white",
    square: "f2",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn007_White_Material003_0",
    type: "pawn",
    color: "white",
    square: "g2",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn008_White_Material003_0",
    type: "pawn",
    color: "white",
    square: "h2",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn009_Black_Material001_0",
    type: "pawn",
    color: "black",
    square: "a7",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn010_Black_Material001_0",
    type: "pawn",
    color: "black",
    square: "b7",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn011_Black_Material001_0",
    type: "pawn",
    color: "black",
    square: "c7",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn012_Black_Material001_0",
    type: "pawn",
    color: "black",
    square: "d7",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn013_Black_Material001_0",
    type: "pawn",
    color: "black",
    square: "e7",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn014_Black_Material001_0",
    type: "pawn",
    color: "black",
    square: "f7",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn015_Black_Material001_0",
    type: "pawn",
    color: "black",
    square: "g7",
    scaleFactor: 1,
  },
  {
    nodeName: "Pawn016_Black_Material001_0",
    type: "pawn",
    color: "black",
    square: "h7",
    scaleFactor: 1,
  },
  {
    nodeName: "Rook002_White_Material003_0",
    type: "rook",
    color: "white",
    square: "a1",
    scaleFactor: 1.1,
  },
  {
    nodeName: "Rook003_White_Material003_0",
    type: "rook",
    color: "white",
    square: "h1",
    scaleFactor: 1.1,
  },
  {
    nodeName: "Rook001_Black_Material001_0",
    type: "rook",
    color: "black",
    square: "a8",
    scaleFactor: 1.1,
  },
  {
    nodeName: "Rook004_Black_Material001_0",
    type: "rook",
    color: "black",
    square: "h8",
    scaleFactor: 1.1,
  },
  {
    nodeName: "Knight_White_Material003_0",
    type: "knight",
    color: "white",
    square: "b1",
    scaleFactor: 1.1,
  },
  {
    nodeName: "Knight001_White_Material003_0",
    type: "knight",
    color: "white",
    square: "g1",
    scaleFactor: 1.1,
  },
  {
    nodeName: "Knight002_Black_Material001_0",
    type: "knight",
    color: "black",
    square: "b8",
    scaleFactor: 1.1,
  },
  {
    nodeName: "Knight003_Black_Material001_0",
    type: "knight",
    color: "black",
    square: "g8",
    scaleFactor: 1.1,
  },
  {
    nodeName: "Bishop001_White_Material003_0",
    type: "bishop",
    color: "white",
    square: "c1",
    scaleFactor: 1.3,
  },
  {
    nodeName: "Bishop002_White_Material003_0",
    type: "bishop",
    color: "white",
    square: "f1",
    scaleFactor: 1.3,
  },
  {
    nodeName: "Bishop003_Black_Material001_0",
    type: "bishop",
    color: "black",
    square: "c8",
    scaleFactor: 1.3,
  },
  {
    nodeName: "Bishop004_Black_Material001_0",
    type: "bishop",
    color: "black",
    square: "f8",
    scaleFactor: 1.3,
  },
  {
    nodeName: "queen001_White_Material003_0",
    type: "queen",
    color: "white",
    square: "d1",
    scaleFactor: 1.6,
  },
  {
    nodeName: "queen002_Black_Material001_0",
    type: "queen",
    color: "black",
    square: "d8",
    scaleFactor: 1.6,
  },
  {
    nodeName: "King_White_Material003_0",
    type: "king",
    color: "white",
    square: "e1",
    scaleFactor: 1.7,
  },
  {
    nodeName: "King001_Black_Material001_0",
    type: "king",
    color: "black",
    square: "e8",
    scaleFactor: 1.7,
  },
];
